pull_request_rules:
  - name: "Automatic merge when CI passes and approved"
    conditions:
      - "#approved-reviews-by>=2"
      - "check-success=your-ci-name"
      - "base=main"
    actions:
      merge: