pull_request_rules:
  - name: Automatic merge when CI passes and approved
    actions:
      merge: 
    conditions:
      - check-success=Codacy Static Code Analysis
      - 'check-success=DeepSource: Python'
      - base=master
